### ISSUE TITLE
Our own numbers

### ISSUE THREAD

**Issue by madpad33** [StevenWeathers/thunderdome-planning-poker#149]
Is there a way to have our own custum number System when we install it locally? 
if yes, is there a foolproof install guide with docker compose? Thanks a lot!

**Comment by StevenWeathers** [comment]
If you're talking about the allowed and default points those are configurable


config.allowedPointValues | CONFIG_POINTS_ALLOWED | List of available point values for creating battles. | 0, 1/2, 2, 3, 5, 8, 13, 20, 40, 100, ?
-- | -- | -- | --
config.defaultPointValues | CONFIG_POINTS_DEFAULT | List of default selected points for new battles. | 1, 2, 3, 5, 8 , 13, ?

**Comment by madpad33** [comment]
Thanks. Yes that's exactly what I meant.

So I just need a way to install it locally. I was not able to make it work.
Is there a good instruction how we can set it up with docker?

We have some docker images running on our synology, but it seems this needs some more work to get it running.

Thanks a lot for some newbie help. We really love the Thunderdome Planning Poker.

Best regards.

Patrick

Am 25.02.2021 um 00:15 schrieb Steven Weathers <notifications@github.com>:

﻿

If you're talking about the allowed and default points those are configurable

config.allowedPointValues       CONFIG_POINTS_ALLOWED   List of available point values for creating battles.    0, 1/2, 2, 3, 5, 8, 13, 20, 40, 100, ?
config.defaultPointValues       CONFIG_POINTS_DEFAULT   List of default selected points for new battles.        1, 2, 3, 5, 8 , 13, ?

**Comment by eivindt** [comment]
It's not very hard to create your own docker-compose file.

The one I use locally looks similar to this (originally based on the one in the repo):
```
version: '3.5'

networks:
  services_net:
    external: true
  asgard:

volumes:
  thunderdome_data:

services:
  thunderdome:
    image: stevenweathers/thunderdome-planning-poker
    networks:
      - services_net
      - asgard
    volumes:
      - /etc/thunderdome:/etc/thunderdome:ro
#    dns: <dns server>
#    dns_search: <domain name>
    expose:
      - "8080"
    depends_on:
      - db
    labels:
      - "traefik.http.routers.thunderdome.rule=PathPrefix(`/thunderdome/`)"
      - "traefik.enable=true"
      - "traefik.http.routers.thunderdome.tls=true"
      - "traefik.http.routers.thunderdome.entrypoints=websecure"

  db:
    image: postgres:12
    restart: always
    environment:
#      POSTGRES_DB: thunderdome
#      POSTGRES_USER: thor
#      POSTGRES_PASSWORD: odinson
    volumes:
      - thunderdome_data:/var/lib/postgresql/data
    networks:
      - asgard
```
This sets up the official docker image for thunderdome, uses a postgres image for the database, but uses an external mail server directly.  The labels are for traefik to proxy traffic to the container automatically.

The commented lines have real values in my setup (and are not commented).


My config file located in `/etc/thunderdome/config.yaml` looks something like this:
```
config:
        allowedPointValues: [ "1", "2", "3", "5", "8", "13", "21", "34", "?" ]
        defaultPointValues: [ "1", "2", "3", "5", "8", "13", "?" ]
        toast_timeout: 3000
admin:
#        email: "<email>"
auth:
        method: "ldap"
        ldap:
# [cut]

http:
#        domain: "domain.name/thunderdome"
        path_prefix: "/thunderdome"
analytics:
        enabled: false
smtp:
#        host: "<mailserver>"
#        sender: "<sender>"
        secure: false
```

As you see, it will also modify what numbers to show.  Again, the commented values have real values in my setup.
