### ISSUE TITLE
Error message when creating guest user

### ISSUE THREAD

**Issue by frazzyfin** [StevenWeathers/thunderdome-planning-poker#172]
When I try and add a guest user, upon entering the name and clicking on 'Register', a banner appears at the top of the web page saying `Error finding your battles`. An entry is added in the docker logs saying `error in reading user cookie :http: named cookie not present`.

**Comment by frazzyfin** [comment]
My config.yaml looks like this:

```
http:
  domain: thunderdome.dev
  port: 9876
  secure_cookie: false
db:
  host: thunderdome_db
  port: 5432
  user: thor
  pass: odinson
  name: thunderdome
```
