### ISSUE TITLE
404 when using `http.path_prefix: /poker`

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#257]
It just says this in webpage: 
![image](https://user-images.githubusercontent.com/29582865/150424430-5cf5c46a-6d9c-4fbf-a9b1-422ccad279ba.png)

And nothing shows up in console log or the container log.

**Comment by felipecrs** [comment]
I cloned the repo, added:

![image](https://user-images.githubusercontent.com/29582865/150427488-e5ca4264-2f48-46f6-bb8a-0131e7e726b6.png)

To docker-compose.yaml. Ran docker-compose up, and the same issue happens.

**Comment by felipecrs** [comment]
I just found out that if I put a trailing slash in the browser it works.

**Comment by felipecrs** [comment]
If you use Kubernetes, it can be worked around with:

```yaml
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: my.domain.com
      paths:
        - path: /poker/ # put a trailing slash here, so that nginx will automatically redirect /poker to /poker/
          pathType: ImplementationSpecific
```
