### ISSUE TITLE
Unable to update optional data of profile

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#361]
This is my Thunderdome configuration:

```yaml
  http:
    domain: hidden
    path_prefix: /poker
  db:
    host: thunderdome-planning-poker-postgresql
    port: 5432
    user: hidden
    pass: hidden
    name: thunderdome
  analytics:
    enabled: false
  config:
    friendly_ui_verbs: true
    show_warrior_rank: true
    allow_guests: false
    allow_registration: false
    organizations_enabled: false
    require_teams: true
  admin:
    email: hidden
  auth:
    method: ldap
    ldap:
      url: hidden
      use_tls: false
      bindname: hidden
      bindpass:
      basedn: hidden
      filter: (&(objectClass=person)(mail=%s))
      mail_attr: mail
      cn_attr: hidden
```

Every time I try to update any optional info in my profile, such as country, company, title, an error pop up in the screen. The following can be seen in the backend logs:

```
{"level":"error","ts":1662404224.8849766,"caller":"api/util.go:338","msg":"Failed authenticating user","version":"2.24.3","username":"hidden@email.com","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/api.(*api).authAndCreateUserLdap\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/api/util.go:338\ngithub.com/StevenWeathers/thunderdome-planning-poker/api.(*api).handleLdapLogin.func1\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/api/auth.go:122\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2084\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux@v0.33.0/mux.go:145\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/server.go:1966"}
```

UI's exception is:

```
Failed to load resource: the server responded with a status of 400 ()
```
