### ISSUE TITLE
[Bug]: Thunderdome can't connect to the DB in the Docker image

### ISSUE THREAD

**Issue by jeberger** [StevenWeathers/thunderdome-planning-poker#721]
### What happened?

Using the following `docker-compose.yml`:

```yaml
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: thunderdome
      POSTGRES_PASSWORD: thunderdome
      POSTGRES_DB: thunderdome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  thunderdome:
    image: stevenweathers/thunderdome-planning-poker:latest
    environment:
      DB_USER: thunderdome
      DB_PASSWORD: thunderdome
      DB_NAME: thunderdome
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "7869:8080"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
```

And starting it with `docker compose up db -d; sleep 10; docker compose up` so that the `db` service will have time to start before thunderdome tries to access it, I get error messages stating that thunderdome failed to connect to the database (see log below).

Note that if I try to access the DB with the `psql` client from another container, the authentication is successful, showing that PostgreSQL is configured correctly:

```
> docker run -it --network thunderdome_default --entrypoint /bin/bash postgres:17
root@51ac70446fee:/# psql -h db -U thunderdome
Password for user thunderdome: 
psql (17.5 (Debian 17.5-1.pgdg120+1))
Type "help" for help.

thunderdome=# 
```

### Self Hosted?

Yes

### Version

Latest

### Relevant log output

```shell
Attaching to db-1, thunderdome-1
db-1           | 2025-06-18 08:39:35.673 UTC [68] FATAL:  password authentication failed for user "thunderdome"
db-1           | 2025-06-18 08:39:35.673 UTC [68] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
db-1           | 2025-06-18 08:39:35.675 UTC [69] FATAL:  password authentication failed for user "thunderdome"
db-1           | 2025-06-18 08:39:35.675 UTC [69] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
thunderdome-1  | {"level":"error","ts":1750235975.6753628,"caller":"db/database.go:78","msg":"migrations error","version":"5.1.0","error":"failed to connect to `user=thunderdome database=thunderdome`: 172.28.0.2:5432 (db): failed SASL auth: FATAL: password authentication failed for user \"thunderdome\" (SQLSTATE 28P01)","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/internal/db.New\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/internal/db/database.go:78\nmain.main\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/main.go:85\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.3/x64/src/runtime/proc.go:283"}
db-1           | 2025-06-18 08:39:35.676 UTC [70] FATAL:  password authentication failed for user "thunderdome"
db-1           | 2025-06-18 08:39:35.676 UTC [70] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
thunderdome-1  | {"level":"error","ts":1750235975.6768305,"caller":"db/database.go:84","msg":"CALL thunderdome.deactivate_all_users error","version":"5.1.0","error":"failed to connect to `user=thunderdome database=thunderdome`: 172.28.0.2:5432 (db): failed SASL auth: FATAL: password authentication failed for user \"thunderdome\" (SQLSTATE 28P01)","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/internal/db.New\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/internal/db/database.go:84\nmain.main\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/main.go:85\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.3/x64/src/runtime/proc.go:283"}
db-1           | 2025-06-18 08:39:35.678 UTC [71] FATAL:  password authentication failed for user "thunderdome"
db-1           | 2025-06-18 08:39:35.678 UTC [71] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
thunderdome-1  | {"level":"error","ts":1750235975.6785438,"caller":"db/database.go:105","msg":"failed to update thunderdome_default estimation scale","version":"5.1.0","error":"failed to connect to `user=thunderdome database=thunderdome`: 172.28.0.2:5432 (db): failed SASL auth: FATAL: password authentication failed for user \"thunderdome\" (SQLSTATE 28P01)","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/internal/db.New\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/internal/db/database.go:105\nmain.main\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/main.go:85\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.3/x64/src/runtime/proc.go:283"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
